// packages/react/src/components/TCard.tsx
import { forwardRef, type HTMLAttributes, type ReactNode } from 'react';
import { tv } from '@treeui/utils';
import type { TCardVariant, TSize } from '../types';

const cardClass = tv({
  base: 't-card',
  variants: {
    variant: {
      outline: 't-card--outline',
      soft: 't-card--soft',
      inset: 't-card--inset',
    },
    size: {
      sm: 't-card--sm',
      md: 't-card--md',
      lg: 't-card--lg',
    },
  },
});

export interface TCardProps extends HTMLAttributes<HTMLDivElement> {
  variant?: TCardVariant;
  size?: TSize;
  header?: ReactNode;
  footer?: ReactNode;
}

export const TCard = forwardRef<HTMLDivElement, TCardProps>(function TCard(
  { variant = 'outline', size = 'md', header, footer, className, children, ...rest },
  ref,
) {
  return (
    <div {...rest} ref={ref} className={cardClass({ variant, size, class: className })}>
      {header ? <div className="t-card__header">{header}</div> : null}
      <div className="t-card__body">{children}</div>
      {footer ? <div className="t-card__footer">{footer}</div> : null}
    </div>
  );
});

// packages/vue/src/components/TCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { TCardVariant, TSize } from '../types/contracts';

const props = withDefaults(
  defineProps<{
    as?: string;
    variant?: TCardVariant;
    size?: TSize;
    title?: string;
  }>(),
  {
    as: 'section',
    variant: 'outline',
    size: 'md',
    title: undefined,
  },
);

const classes = computed(() => [
  't-card',
  `t-card--${props.variant}`,
  `t-card--${props.size}`,
]);

const hasHeader = computed(() => !!props.title);
</script>

<template>
  <component
    :is="as"
    :class="classes"
  >
    <header
      v-if="$slots.header || hasHeader || $slots.actions"
      class="t-card__header"
    >
      <slot name="header">
        <span
          v-if="title"
          class="t-card__title"
        >
          {{ title }}
        </span>
      </slot>
      <span
        v-if="$slots.actions"
        class="t-card__actions"
      >
        <slot name="actions" />
      </span>
    </header>
    <div class="t-card__body">
      <slot />
    </div>
    <footer
      v-if="$slots.footer"
      class="t-card__footer"
    >
      <slot name="footer" />
    </footer>
  </component>
</template>
