// packages/react/src/components/TInput.tsx
import { forwardRef, type InputHTMLAttributes, type ReactNode } from 'react';
import { tv } from '@treeui/utils';
import type { TSize } from '../types';

const inputClass = tv({
  base: 't-input',
  variants: {
    size: {
      sm: 't-input--sm',
      md: 't-input--md',
      lg: 't-input--lg',
    },
  },
});

export interface TInputProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'prefix'> {
  size?: TSize;
  invalid?: boolean;
  prefix?: ReactNode;
  suffix?: ReactNode;
}

export const TInput = forwardRef<HTMLInputElement, TInputProps>(function TInput(
  { size = 'md', invalid = false, disabled = false, prefix, suffix, className, ...rest },
  ref,
) {
  return (
    <label
      className={inputClass({
        size,
        class: [className, { 'is-invalid': invalid, 'is-disabled': disabled }],
      })}
    >
      {prefix ? (
        <span className="t-input__slot t-input__slot--prefix">{prefix}</span>
      ) : null}
      <input
        {...rest}
        ref={ref}
        className="t-input__field"
        disabled={disabled}
        aria-invalid={invalid || undefined}
      />
      {suffix ? (
        <span className="t-input__slot t-input__slot--suffix">{suffix}</span>
      ) : null}
    </label>
  );
});

// packages/vue/src/components/TInput.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { TSize } from '../types/contracts';
import TSpinner from './TSpinner.vue';

defineOptions({
  inheritAttrs: false,
});

const props = withDefaults(
  defineProps<{
    modelValue?: string | number;
    size?: TSize;
    disabled?: boolean;
    loading?: boolean;
    invalid?: boolean;
    type?: string;
    placeholder?: string;
  }>(),
  {
    modelValue: '',
    size: 'md',
    disabled: false,
    loading: false,
    invalid: false,
    type: 'text',
    placeholder: '',
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const attrs = useAttrs();

const rootClasses = computed(() => [
  't-input',
  `t-input--${props.size}`,
  {
    'is-disabled': props.disabled,
    'is-invalid': props.invalid,
    'is-loading': props.loading,
  },
  attrs.class,
]);

const rootStyle = computed(() => attrs.style);

const inputAttrs = computed(() => {
  const { class: _class, style: _style, ...rest } = attrs;
  return rest;
});

const stringValue = computed(() => `${props.modelValue ?? ''}`);

const onInput = (event: Event) => {
  emit('update:modelValue', (event.target as HTMLInputElement).value);
};
</script>

<template>
  <label
    :class="rootClasses"
    :style="rootStyle"
  >
    <span
      v-if="$slots.prefix"
      class="t-input__slot t-input__slot--prefix"
    >
      <slot name="prefix" />
    </span>
    <input
      v-bind="inputAttrs"
      class="t-input__field"
      :type="type"
      :value="stringValue"
      :placeholder="placeholder"
      :disabled="disabled"
      :aria-invalid="invalid || undefined"
      @input="onInput"
    >
    <TSpinner
      v-if="loading"
      size="sm"
      label="Loading"
    />
    <span
      v-if="$slots.suffix"
      class="t-input__slot t-input__slot--suffix"
    >
      <slot name="suffix" />
    </span>
  </label>
</template>
